"""基础表情包库"""

from typing import Dict, List

from app.models.sticker import StickerEmotion, StickerPersonalityMatch, StickerType

# 基础表情包库
DEFAULT_STICKERS: List[Dict] = [
    # ========== 情绪类表情包 ==========
    # 开心
    {
        "name": "开心拍手",
        "type": StickerType.EMOTION,
        "url": "https://cdn.example.com/stickers/happy/clap.gif",
        "emotion": StickerEmotion.HAPPY,
        "personality_match": StickerPersonalityMatch.ALL,
        "tags": ["开心", "高兴", "拍手", "庆祝"],
        "keywords": ["开心", "高兴", "好", "棒", "赞", "庆祝", "恭喜"],
        "description": "开心地拍手叫好",
        "source": "官方",
        "file_format": "gif",
        "base_weight": 1.2,
    },
    {
        "name": "开心蹦跳",
        "type": StickerType.EMOTION,
        "url": "https://cdn.example.com/stickers/happy/jump.gif",
        "emotion": StickerEmotion.HAPPY,
        "personality_match": StickerPersonalityMatch.CHEERFUL,
        "tags": ["开心", "蹦跳", "兴奋"],
        "keywords": ["开心", "超开心", "太棒了", "耶"],
        "description": "开心到蹦起来",
        "source": "官方",
        "file_format": "gif",
        "base_weight": 1.1,
    },
    {
        "name": "微笑",
        "type": StickerType.EMOTION,
        "url": "https://cdn.example.com/stickers/happy/smile.png",
        "emotion": StickerEmotion.HAPPY,
        "personality_match": StickerPersonalityMatch.CALM,
        "tags": ["微笑", "开心", "友善"],
        "keywords": ["好的", "没问题", "可以", "微笑"],
        "description": "温和的微笑",
        "source": "官方",
        "file_format": "png",
        "base_weight": 1.0,
    },
    # 兴奋
    {
        "name": "闪闪发光",
        "type": StickerType.EMOTION,
        "url": "https://cdn.example.com/stickers/excited/sparkle.gif",
        "emotion": StickerEmotion.EXCITED,
        "personality_match": StickerPersonalityMatch.ALL,
        "tags": ["兴奋", "期待", "闪闪发光"],
        "keywords": ["期待", "哇", "好棒", "厉害", "惊艳"],
        "description": "眼睛闪闪发光充满期待",
        "source": "官方",
        "file_format": "gif",
        "base_weight": 1.1,
    },
    {
        "name": "打call",
        "type": StickerType.EMOTION,
        "url": "https://cdn.example.com/stickers/excited/call.gif",
        "emotion": StickerEmotion.EXCITED,
        "personality_match": StickerPersonalityMatch.CHEERFUL,
        "tags": ["打call", "加油", "助威"],
        "keywords": ["加油", "冲啊", "支持你", "打call"],
        "description": "疯狂打call",
        "source": "官方",
        "file_format": "gif",
        "base_weight": 1.2,
    },
    # 难过
    {
        "name": "委屈巴巴",
        "type": StickerType.EMOTION,
        "url": "https://cdn.example.com/stickers/sad/pout.gif",
        "emotion": StickerEmotion.SAD,
        "personality_match": StickerPersonalityMatch.ALL,
        "tags": ["难过", "委屈", "不开心"],
        "keywords": ["难过", "伤心", "委屈", "不开心", "呜"],
        "description": "委屈地撅嘴",
        "source": "官方",
        "file_format": "gif",
        "base_weight": 1.0,
    },
    {
        "name": "流泪",
        "type": StickerType.EMOTION,
        "url": "https://cdn.example.com/stickers/sad/cry.png",
        "emotion": StickerEmotion.SAD,
        "personality_match": StickerPersonalityMatch.ALL,
        "tags": ["流泪", "难过", "哭"],
        "keywords": ["哭", "流泪", "好难过", "难受"],
        "description": "默默流泪",
        "source": "官方",
        "file_format": "png",
        "base_weight": 0.9,
    },
    # 生气
    {
        "name": "气鼓鼓",
        "type": StickerType.EMOTION,
        "url": "https://cdn.example.com/stickers/angry/puff.gif",
        "emotion": StickerEmotion.ANGRY,
        "personality_match": StickerPersonalityMatch.ALL,
        "tags": ["生气", "气鼓鼓", "不高兴"],
        "keywords": ["生气", "哼", "气死我了", "不开心"],
        "description": "气得脸都鼓起来了",
        "source": "官方",
        "file_format": "gif",
        "base_weight": 1.0,
    },
    {
        "name": "怒视",
        "type": StickerType.EMOTION,
        "url": "https://cdn.example.com/stickers/angry/glare.png",
        "emotion": StickerEmotion.ANGRY,
        "personality_match": StickerPersonalityMatch.SARCASTIC,
        "tags": ["生气", "怒视", "不满"],
        "keywords": ["哦", "是吗", "呵呵", "你再说一遍"],
        "description": "冷冷地怒视",
        "source": "官方",
        "file_format": "png",
        "base_weight": 0.8,
    },
    # 惊讶
    {
        "name": "惊呆",
        "type": StickerType.EMOTION,
        "url": "https://cdn.example.com/stickers/surprised/shock.gif",
        "emotion": StickerEmotion.SURPRISED,
        "personality_match": StickerPersonalityMatch.ALL,
        "tags": ["惊讶", "惊呆", "震惊"],
        "keywords": ["哇", "真的吗", "震惊", "惊呆了", "不会吧"],
        "description": "震惊到下巴都掉了",
        "source": "官方",
        "file_format": "gif",
        "base_weight": 1.1,
    },
    {
        "name": "哇哦",
        "type": StickerType.EMOTION,
        "url": "https://cdn.example.com/stickers/surprised/wow.png",
        "emotion": StickerEmotion.SURPRISED,
        "personality_match": StickerPersonalityMatch.CHEERFUL,
        "tags": ["惊讶", "哇哦", "赞叹"],
        "keywords": ["哇哦", "厉害", "牛", "太强了"],
        "description": "哇哦的表情",
        "source": "官方",
        "file_format": "png",
        "base_weight": 1.0,
    },
    # 困惑
    {
        "name": "问号脸",
        "type": StickerType.EMOTION,
        "url": "https://cdn.example.com/stickers/confused/question.gif",
        "emotion": StickerEmotion.CONFUSED,
        "personality_match": StickerPersonalityMatch.ALL,
        "tags": ["困惑", "疑问", "不懂"],
        "keywords": ["？", "什么", "不懂", "啥意思", "是吗"],
        "description": "满头问号",
        "source": "官方",
        "file_format": "gif",
        "base_weight": 1.2,
    },
    {
        "name": "挠头",
        "type": StickerType.EMOTION,
        "url": "https://cdn.example.com/stickers/confused/scratch.png",
        "emotion": StickerEmotion.CONFUSED,
        "personality_match": StickerPersonalityMatch.ALL,
        "tags": ["困惑", "挠头", "思考"],
        "keywords": ["等一下", "我想想", "有点懵", "挠头"],
        "description": "困惑地挠头",
        "source": "官方",
        "file_format": "png",
        "base_weight": 1.0,
    },
    # 喜爱
    {
        "name": "爱心眼",
        "type": StickerType.EMOTION,
        "url": "https://cdn.example.com/stickers/loving/heart.gif",
        "emotion": StickerEmotion.LOVING,
        "personality_match": StickerPersonalityMatch.ALL,
        "tags": ["喜欢", "爱心", "可爱"],
        "keywords": ["喜欢", "爱你", "好可爱", "萌", "心动"],
        "description": "眼睛变成爱心",
        "source": "官方",
        "file_format": "gif",
        "base_weight": 1.3,
    },
    {
        "name": "比心",
        "type": StickerType.EMOTION,
        "url": "https://cdn.example.com/stickers/loving/love.png",
        "emotion": StickerEmotion.LOVING,
        "personality_match": StickerPersonalityMatch.ALL,
        "tags": ["比心", "爱你", "感谢"],
        "keywords": ["比心", "爱你", "谢谢", "么么哒"],
        "description": "比个小心心",
        "source": "官方",
        "file_format": "png",
        "base_weight": 1.2,
    },
    # 尴尬
    {
        "name": "流汗黄豆",
        "type": StickerType.EMOTION,
        "url": "https://cdn.example.com/stickers/embarrassed/sweat.gif",
        "emotion": StickerEmotion.EMBARRASSED,
        "personality_match": StickerPersonalityMatch.ALL,
        "tags": ["尴尬", "流汗", "无语"],
        "keywords": ["尴尬", "汗", "无语", "这"],
        "description": "尴尬地流汗",
        "source": "官方",
        "file_format": "gif",
        "base_weight": 1.1,
    },
    {
        "name": "捂脸",
        "type": StickerType.EMOTION,
        "url": "https://cdn.example.com/stickers/embarrassed/facepalm.png",
        "emotion": StickerEmotion.EMBARRASSED,
        "personality_match": StickerPersonalityMatch.ALL,
        "tags": ["尴尬", "捂脸", "不好意思"],
        "keywords": ["哎呀", "不好意思", "我错了", "捂脸"],
        "description": "害羞地捂脸",
        "source": "官方",
        "file_format": "png",
        "base_weight": 1.0,
    },
    # 骄傲
    {
        "name": "叉腰骄傲",
        "type": StickerType.EMOTION,
        "url": "https://cdn.example.com/stickers/proud/proud.gif",
        "emotion": StickerEmotion.PROUD,
        "personality_match": StickerPersonalityMatch.ALL,
        "tags": ["骄傲", "得意", "叉腰"],
        "keywords": ["厉害吧", "我超棒", "得意", "骄傲"],
        "description": "叉腰骄傲脸",
        "source": "官方",
        "file_format": "gif",
        "base_weight": 1.0,
    },
    {
        "name": "傲娇抬头",
        "type": StickerType.EMOTION,
        "url": "https://cdn.example.com/stickers/proud/haughty.png",
        "emotion": StickerEmotion.PROUD,
        "personality_match": StickerPersonalityMatch.SARCASTIC,
        "tags": ["傲娇", "得意", "哼"],
        "keywords": ["那当然", "也不看是谁", "傲娇"],
        "description": "傲娇地抬起头",
        "source": "官方",
        "file_format": "png",
        "base_weight": 0.9,
    },
    # 放松
    {
        "name": "喝茶",
        "type": StickerType.EMOTION,
        "url": "https://cdn.example.com/stickers/relaxed/tea.gif",
        "emotion": StickerEmotion.RELAXED,
        "personality_match": StickerPersonalityMatch.CALM,
        "tags": ["放松", "喝茶", "悠闲"],
        "keywords": ["慢慢来", "不急", "喝茶", "淡定"],
        "description": "悠闲地喝茶",
        "source": "官方",
        "file_format": "gif",
        "base_weight": 1.0,
    },
    {
        "name": "摸鱼",
        "type": StickerType.EMOTION,
        "url": "https://cdn.example.com/stickers/relaxed/fish.png",
        "emotion": StickerEmotion.RELAXED,
        "personality_match": StickerPersonalityMatch.ALL,
        "tags": ["摸鱼", "划水", "休息"],
        "keywords": ["摸鱼", "划水", "休息一下", "好累"],
        "description": "快乐摸鱼",
        "source": "官方",
        "file_format": "png",
        "base_weight": 1.1,
    },
    # 搞怪
    {
        "name": "狗头",
        "type": StickerType.EMOTION,
        "url": "https://cdn.example.com/stickers/silly/dog.png",
        "emotion": StickerEmotion.SILLY,
        "personality_match": StickerPersonalityMatch.ALL,
        "tags": ["狗头", "滑稽", "搞怪"],
        "keywords": ["狗头", "滑稽", "doge", "保命"],
        "description": "经典狗头表情",
        "source": "官方",
        "file_format": "png",
        "base_weight": 1.5,
    },
    {
        "name": "沙雕跳舞",
        "type": StickerType.EMOTION,
        "url": "https://cdn.example.com/stickers/silly/dance.gif",
        "emotion": StickerEmotion.SILLY,
        "personality_match": StickerPersonalityMatch.CHEERFUL,
        "tags": ["搞怪", "跳舞", "沙雕"],
        "keywords": ["哈哈哈", "笑死", "逗你玩", "沙雕"],
        "description": "沙雕魔性跳舞",
        "source": "官方",
        "file_format": "gif",
        "base_weight": 1.2,
    },
    # 安慰
    {
        "name": "摸摸头",
        "type": StickerType.EMOTION,
        "url": "https://cdn.example.com/stickers/supportive/pat.gif",
        "emotion": StickerEmotion.SUPPORTIVE,
        "personality_match": StickerPersonalityMatch.ALL,
        "tags": ["安慰", "摸摸头", "鼓励"],
        "keywords": ["摸摸头", "不哭", "加油", "我在"],
        "description": "温柔地摸摸头",
        "source": "官方",
        "file_format": "gif",
        "base_weight": 1.3,
    },
    {
        "name": "拥抱",
        "type": StickerType.EMOTION,
        "url": "https://cdn.example.com/stickers/supportive/hug.png",
        "emotion": StickerEmotion.SUPPORTIVE,
        "personality_match": StickerPersonalityMatch.CALM,
        "tags": ["拥抱", "安慰", "支持"],
        "keywords": ["抱抱", "没事的", "有我在", "别担心"],
        "description": "温暖的拥抱",
        "source": "官方",
        "file_format": "png",
        "base_weight": 1.1,
    },
    # ========== 反应类表情包 ==========
    {
        "name": "收到",
        "type": StickerType.REACTION,
        "url": "https://cdn.example.com/stickers/reaction/ok.gif",
        "emotion": None,
        "personality_match": StickerPersonalityMatch.ALL,
        "tags": ["收到", "明白", "OK"],
        "keywords": ["收到", "好的", "明白", "没问题", "ok"],
        "description": "收到指令",
        "source": "官方",
        "file_format": "gif",
        "base_weight": 1.1,
    },
    {
        "name": "点赞",
        "type": StickerType.REACTION,
        "url": "https://cdn.example.com/stickers/reaction/like.png",
        "emotion": None,
        "personality_match": StickerPersonalityMatch.ALL,
        "tags": ["点赞", "很棒", "厉害"],
        "keywords": ["赞", "棒", "厉害", "666", "牛"],
        "description": "点赞认可",
        "source": "官方",
        "file_format": "png",
        "base_weight": 1.2,
    },
    {
        "name": "OK",
        "type": StickerType.REACTION,
        "url": "https://cdn.example.com/stickers/reaction/ok_hand.png",
        "emotion": None,
        "personality_match": StickerPersonalityMatch.ALL,
        "tags": ["ok", "可以", "没问题"],
        "keywords": ["ok", "可以", "行", "没问题"],
        "description": "OK手势",
        "source": "官方",
        "file_format": "png",
        "base_weight": 1.0,
    },
    {
        "name": "再见",
        "type": StickerType.REACTION,
        "url": "https://cdn.example.com/stickers/reaction/bye.gif",
        "emotion": None,
        "personality_match": StickerPersonalityMatch.ALL,
        "tags": ["再见", "拜拜", "下次见"],
        "keywords": ["再见", "拜拜", "我走了", "下次聊"],
        "description": "挥手再见",
        "source": "官方",
        "file_format": "gif",
        "base_weight": 1.0,
    },
    # ========== 梗图类表情包 ==========
    {
        "name": "听我说谢谢你",
        "type": StickerType.MEME,
        "url": "https://cdn.example.com/stickers/meme/thankyou.png",
        "emotion": None,
        "personality_match": StickerPersonalityMatch.ALL,
        "tags": ["谢谢", "感恩", "梗图"],
        "keywords": ["谢谢", "感谢", "听我说谢谢你"],
        "description": "听我说谢谢你梗图",
        "source": "网络",
        "file_format": "png",
        "base_weight": 0.9,
    },
    {
        "name": "你懂我的意思吧",
        "type": StickerType.MEME,
        "url": "https://cdn.example.com/stickers/meme/understand.png",
        "emotion": None,
        "personality_match": StickerPersonalityMatch.SARCASTIC,
        "tags": ["懂我意思", "暗示", "梗图"],
        "keywords": ["你懂的", "暗示", "对吧", "明白我意思吧"],
        "description": "你懂我的意思吧梗图",
        "source": "网络",
        "file_format": "png",
        "base_weight": 0.8,
    },
    {
        "name": "我想开了",
        "type": StickerType.MEME,
        "url": "https://cdn.example.com/stickers/meme/enlightened.png",
        "emotion": None,
        "personality_match": StickerPersonalityMatch.ALL,
        "tags": ["想开了", "佛系", "无所谓"],
        "keywords": ["算了", "无所谓", "想开了", "随便吧"],
        "description": "我想开了佛系带字图",
        "source": "网络",
        "file_format": "png",
        "base_weight": 1.0,
    },
]


# 标签系统配置
STICKER_TAG_CATEGORIES = {
    "情绪": [
        "开心",
        "难过",
        "生气",
        "惊讶",
        "困惑",
        "害羞",
        "兴奋",
        "平静",
        "激动",
        "失望",
        "期待",
        "焦虑",
        "骄傲",
        "嫉妒",
        "感激",
        "思念",
    ],
    "场景": [
        "问候",
        "告别",
        "感谢",
        "道歉",
        "祝贺",
        "鼓励",
        "安慰",
        "调侃",
        "吐槽",
        "正经",
        "搞笑",
        "卖萌",
        "耍帅",
        "无奈",
        "尴尬",
        "求助",
    ],
    "风格": [
        "可爱",
        "沙雕",
        "炫酷",
        "文艺",
        "复古",
        "清新",
        "暗黑",
        "萌系",
        "写实",
        "卡通",
        "手绘",
        "3D",
        "像素",
        "蒸汽波",
        "赛博朋克",
    ],
    "适用人群": ["通用", "男生", "女生", "情侣", "朋友", "同事", "长辈", "晚辈"],
    "节日": [
        "春节",
        "元宵",
        "清明",
        "端午",
        "中秋",
        "国庆",
        "圣诞",
        "元旦",
        "情人节",
        "儿童节",
        "劳动节",
        "教师节",
        "母亲节",
        "父亲节",
    ],
}
